development:
  server: "http://localhost:9292/faye"
  secret_token: "valaapp"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://vala-app-faye.herokuapp.com/faye"
  secret_token: "valaapp"
  signature_expiration: 3600 # one hour
